language: node_js
node_js:
  - node

before_install:
  - npm install -g bower web-component-tester
  - bower install
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start

script: wct --sauce 'default' --sauce-username $SAUCE_USERNAME --sauce-access-key $SAUCE_ACCESS_KEY
